// web server request ko receive krke serve krta h
//to create server this is the code
//default port ofhttp is 80 , it helps user to access the service without specifying the port number in the url
//create server m sirf ek callback function ata h or is callback m do hote h ek require(req) or request(res)

const http = require("http");
//creating server
const server = http.createServer((req, res) => {
    //sending Response
  res.write("Response generated by the server");
  res.end();
});
//server listening to port 3000
//ip of local host
server.listen(3000, "127.0.0.1", () => {
  console.log("Server is Running.....");
});

// to see on web brower write this http://127.0.0.1:3000/ on edge but this code must also be running on vsc (terminal)